# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faaf0e2692360b98f303aafe87da9de12aad4c5629a17f888e9b35163d28e62cae33581ad39cdab96ba79c98df67c72a54fa495ef4bc670d3c08e7fd1a571cc0

test:
  secret_key_base: 29e9276e54dd22a353003be26152ce592dceac2754d0ee830aec4d740616ef9e83e171625efcd78578ffadc67199c7d9b126784f9a72b668379d539225473117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
